version: 0.2

phases:
install:
  runtime-versions:
    python: 3.11
  commands:
    - echo "Starting Docker"
    - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
    - timeout 30 sh -c "until docker info; do echo .; sleep 1; done"
    - curl -L -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.34.0/2025-05-22/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - export PATH=$PWD:$PATH
    - python -m pip install --upgrade pip awscli pytest
    - yum install -y jq || (apt-get update && apt-get -y install jq)
    
  pre_build:
    commands:
      - TAG=$(date +%Y-%m-%d.%H.%M.%S)
      - sed -i "s@CONTAINER_IMAGE@$REPOSITORY_URI:$TAG@g" simple_jwt_api.yml
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $(echo $REPOSITORY_URI | cut -d/ -f1)
      - pip install -r requirements.txt

  build:
    commands:
      - docker build -t $REPOSITORY_URI:$TAG .

  post_build:
    commands:
      - docker push $REPOSITORY_URI:$TAG
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION --role-arn $EKS_KUBECTL_ROLE_ARN
      - kubectl apply -f simple_jwt_api.yml
      - printf '[{"name":"simple_jwt_api","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > build.json

artifacts:
  files:
    - build.json

env:
  parameter-store:
    JWT_SECRET: JWT_SECRET