apiVersion: v1
kind: Service
metadata:
  name: simple-jwt-api
spec:
  type: LoadBalancer
  selector:
    app: simple-jwt-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-jwt-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-jwt-api
  template:
    metadata:
      labels:
        app: simple-jwt-api
    spec:
      containers:
        - name: simple-jwt-api
          image: 352567617413.dkr.ecr.us-east-2.amazonaws.com/udacity-flask-pipeline-ecrdockerrepository-cnkep4ghobw3:manual
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              value: "myjwtsecret"
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false